chore(ci): test PR against nim-libp2p and nim-lsquic

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -64,18 +64,8 @@ jobs:
         with:
           submodules: "recursive"
 
-      - name: Restore llvm-mingw (Windows) from cache
-        if: runner.os == 'Windows'
-        id: windows-mingw-cache
-        uses: actions/cache@v4
-        with:
-          path: external/mingw-${{ matrix.platform.cpu }}
-          key: 'mingw-llvm-17-${{ matrix.platform.cpu }}'
-
       - name: Install llvm-mingw dependency (Windows)
-        if: >
-          steps.windows-mingw-cache.outputs.cache-hit != 'true' &&
-          runner.os == 'Windows'
+        if: runner.os == 'Windows'
         run: |
           mkdir -p external
           MINGW_BASE="https://github.com/mstorsjo/llvm-mingw/releases/download/20230905"
@@ -84,7 +74,7 @@ jobs:
           7z x -y "external/mingw-${{ matrix.platform.cpu }}.zip" -oexternal/mingw-${{ matrix.platform.cpu }}/
           mv external/mingw-${{ matrix.platform.cpu }}/**/* ./external/mingw-${{ matrix.platform.cpu }}
 
-      - name: Path to cached dependencies (Windows)
+      - name: Add llvm-mingw to path (Windows)
         if: >
           runner.os == 'Windows'
         run: |
@@ -106,18 +96,7 @@ jobs:
           shell: ${{ matrix.shell }}
           nim_ref: ${{ matrix.nim.ref }}
 
-      - name: Restore deps from cache
-        id: deps-cache
-        uses: actions/cache@v3
-        with:
-          path: nimbledeps
-          # Using nim.ref as a simple way to differentiate between nimble using the "pkgs" or "pkgs2" directories.
-          # The change happened on Nimble v0.14.0. Also forcing the deps to be reinstalled on each os and cpu.
-          key: nimbledeps-${{ matrix.nim.ref }}-${{ matrix.builder }}-${{ matrix.platform.cpu }}-${{ hashFiles('.pinned') }} # hashFiles returns a different value on windows
-
-
       - name: Install deps
-        if: ${{ steps.deps-cache.outputs.cache-hit != 'true' }}
         run: |
           nimble install
 
@@ -143,3 +122,103 @@ jobs:
           fi
 
           nimble test --styleCheck:off --verbose --debug
+
+      - name: Checkout nim-libp2p
+        uses: actions/checkout@v6
+        with:
+          repository: vacp2p/nim-libp2p
+          path: downstream/nim-libp2p
+
+      - name: Checkout nim-lsquic
+        uses: actions/checkout@v6
+        with:
+          repository: vacp2p/nim-lsquic
+          path: downstream/nim-lsquic
+          submodules: "recursive"
+
+      - name: Run downstream crypto compatibility checks
+        env:
+          BORINGSSL_REPO: ${{ github.event.pull_request.head.repo.full_name || github.repository }}
+          BORINGSSL_COMMIT: ${{ github.event.pull_request.head.sha || github.sha }}
+          DOWNSTREAM_ROOT: ${{ github.workspace }}/downstream
+        run: |
+          export NIMFLAGS="${NIMFLAGS:-} --mm:${{ matrix.nim.memory_management }}"
+
+          if [[ '${{ runner.os }}' == 'Windows' ]]; then
+            export NIMFLAGS="${NIMFLAGS} --cc:clang"
+          fi
+
+          BORINGSSL_DEP="https://github.com/${BORINGSSL_REPO}.git#${BORINGSSL_COMMIT}"
+          echo "Testing downstream projects against ${BORINGSSL_DEP}"
+
+          update_boringssl_dependency() {
+            local nimble_file="$1"
+            local tmp_file="${nimble_file}.tmp"
+            local repo_dep_re='"https://github\.com/vacp2p/nim-boringssl(\.git)?(#[^"]+|[[:space:]][^"]*)?"'
+            local package_dep_re='"boringssl([[:space:]][^"]*)?"'
+            local line updated=0
+
+            : > "$tmp_file"
+            while IFS= read -r line || [[ -n "$line" ]]; do
+              if [[ $updated -eq 0 && $line =~ $repo_dep_re ]]; then
+                line="${line/${BASH_REMATCH[0]}/\"${BORINGSSL_DEP}\"}"
+                updated=1
+              elif [[ $updated -eq 0 && $line =~ $package_dep_re ]]; then
+                line="${line/${BASH_REMATCH[0]}/\"${BORINGSSL_DEP}\"}"
+                updated=1
+              fi
+
+              printf '%s\n' "$line" >> "$tmp_file"
+            done < "$nimble_file"
+
+            if [[ $updated -eq 0 ]]; then
+              rm -f "$tmp_file"
+              echo "Could not find a nim-boringssl dependency in ${nimble_file}" >&2
+              return 1
+            fi
+
+            mv "$tmp_file" "$nimble_file"
+            echo "Updated ${nimble_file} to depend on ${BORINGSSL_DEP}"
+          }
+
+          run_libp2p() {
+            cd "${DOWNSTREAM_ROOT}/nim-libp2p" &&
+              update_boringssl_dependency libp2p.nimble &&
+              nimble --nimbleDir:"${RUNNER_TEMP}/nimble-libp2p" --localdeps --accept install &&
+              "${MAKE_CMD:-make}" TEST_JOBS=1 test crypto
+          }
+
+          run_lsquic() {
+            cd "${DOWNSTREAM_ROOT}/nim-lsquic" &&
+              update_boringssl_dependency lsquic.nimble &&
+              nimble --nimbleDir:"${RUNNER_TEMP}/nimble-lsquic" --localdeps --accept install &&
+              nimble --nimbleDir:"${RUNNER_TEMP}/nimble-lsquic" --localdeps test
+          }
+
+          run_with_breaking_change_alert() {
+            local project="$1"
+            shift
+
+            if "$@"; then
+              echo "${project} downstream crypto compatibility check passed"
+            else
+              echo "::error title=Breaking downstream change::${project} failed to compile or pass crypto tests against ${BORINGSSL_DEP}; this PR is a breaking change."
+              return 1
+            fi
+          }
+
+          run_with_breaking_change_alert nim-libp2p run_libp2p &
+          libp2p_pid=$!
+          run_with_breaking_change_alert nim-lsquic run_lsquic &
+          lsquic_pid=$!
+
+          set +e
+          wait "$libp2p_pid"
+          libp2p_status=$?
+          wait "$lsquic_pid"
+          lsquic_status=$?
+          set -e
+
+          if [[ $libp2p_status -ne 0 || $lsquic_status -ne 0 ]]; then
+            exit 1
+          fi
